### ISSUE TITLE
Create proof of concept

### ISSUE THREAD

**Issue by jkleinsc** [nolanlawson/pouchdb-with-service-workers#3]
I would like to start working on a proof of concept and as has been suggested, I'm putting together a meta issue to track the work that needs to be done.

Here are the tasks I think that need to be done in order to put together a fully operational proof of concept.
- [X] New PouchDB adapter to proxy PouchDB requests to Service Worker (possibly use or adapt https://github.com/nolanlawson/worker-pouch) - #4 
- [ ] New PouchDB plugin to encapsulate Service Worker logic for local and remote changes - #5
- [ ] Server side push example (maybe build using https://github.com/pouchdb/express-pouchdb) - #6
- [ ] Client side example that uses all of the above - #7 

I think at a high level those are the tasks that need to be done.  Feel free to weigh in @nolanlawson @gr2m @garrensmith if I missed something.

**Comment by jkleinsc** [comment]
[worker-pouch](https://github.com/nolanlawson/worker-pouch) has been updated to work with Service Workers.  Additionally I have a working version of server side push that I am implementing in HospitalRun.  Once I have it complete there I will try to extract it out into something that can be used here.

**Comment by jkleinsc** [comment]
I just put up https://github.com/jkleinsc/telegraph/, which provides a proof of concept for what has been discussed here.  There are still some changes that need to be made for #5, which now that I have finished a proof of concept, I think belong in [worker-pouch](https://github.com/pouchdb-community/worker-pouch) vs another plugin.

cc @rmehner @garrensmith @gr2m @janl @nolanlawson
